config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :posts, except: %i[new edit] do
    resources :comments, only: %i[create update destroy]
  end
  resources :users, only: %i[index show] do
    resources :relationships, only: %i[create] do
      collection do
        patch :accept
        patch :decline
        delete :unfriend
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :title, length: { maximum: 250 }, uniqueness: { case_sensitive: false }
    validates :content
  end

  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id

  enum status: { pending: 0,  approved: 1, rejected: -1 }

  scope :friends, -> { where(status: :approved) }
  scope :pendings, -> { where(status: :pending) }
  scope :not_friends, -> { where(status: :rejected) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_sent, foreign_key: :sender_id, class_name: 'Relationship'
  has_many :friend_request, foreign_key: :receiver_id, class_name: 'Relationship'
  has_many :friends, -> { merge(Relationship.friends) }, through: :friend_sent, source: :receiver
  has_many :pending_requests, -> { merge(Relationship.pendings) }, through: :friend_sent, source: :receiver
  has_many :received_requests, -> { merge(Relationship.pendings) }, through: :friend_request, source: :sender

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :confirmable

  def friend_and_own_posts
    friend_and_own_posts = []


    friends.each do |friend|
      friend.posts.each do |post|
        friend_and_own_posts << post
      end
    end

    posts.each do |post|
      next if post.new_record?
      friend_and_own_posts << post
    end

    friend_and_own_posts.uniq.sort_by(&:created_at).reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def layout_by_resource
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post
  before_action :load_comment, only: %i[update destroy]
  
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = @post.id
    @comment.save
    redirect_to post_path(@post.id)
  end

  def update
    if @comment.update_attributes comment_params
      redirect_to post_path(@post.id)
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def load_post
    @post = Post.find_by(id: params[:post_id])
  end

  def load_comment
    @comment = current_user.comments.find_by(id: params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: %i[show edit update destroy]

  def index
    @post = current_user.posts.build
    @posts = current_user.friend_and_own_posts
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = current_user.comments.build(post_id: @post.id)
  end

  def create
    @post = current_user.posts.build post_params
    respond_to do |format|
      if @post.save
        format.js do
          flash[:success] = 'Create successfully!'
          redirect_to posts_path
        end
      else
        format.js
      end
    end
  end

  def update
    binding.pry
    respond_to do |format|
      if @post.update_attributes post_params
        format.js do
          flash[:success] = 'Update successfully!'
          redirect_to posts_path
        end
      else
        format.js
      end
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Destroy successfully!'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(%i[id title content image])
  end

  def load_post
    @post = current_user.posts.find_by(id: params[:id])
    return if @post
    flash[:error] = 'Not found data!'
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages(obj)
    return if obj.errors.blank?

    content_tag(:div, class: 'error-mesages') do
      obj.errors.full_messages.each { |msg| concat(content_tag(:li, msg)) }
    end
  end

  def flash_messae_class(flash_type)
    return 'success' if flash_type == 'success'
    return 'infor' if flash_type == 'notice'
    return 'danger' if flash_type == 'error'
    return 'warning' if flash_type == 'alert'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_image_url(image_url)
    image_url ? image_url : 'post_default.png'
  end
end

app/views/layouts/_sidenav.html.slim
nav#sideNav.navbar.navbar-expand-lg.navbar-dark.bg-primary.fixed-top
  .navbar-brand
    = image_tag 'default_avatar.png', class: 'img-fluid img-profile rounded-circle mx-auto mb-2' 
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav
      li.nav-item
        = link_to edit_user_registration_path, class: 'nav-link'
          i.fas.fa-user-circle>
          = current_user.name
      li.nav-item
        = link_to posts_path, class: 'nav-link'
          i.far.fa-newspaper>
          | New Feed
      li.nav-item
        = link_to destroy_user_session_path, method: :delete, class: 'nav-link'
          i.fas.fa-sign-out-alt>
          | Log out

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Socify
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/sidenav'
    = render 'shared/flash_messages'
    = yield

app/views/layouts/devise.html.slim
doctype html
html
  head
    title
      | Socify
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'devise', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/posts/_form.html.slim
= form_with model: post, url: posts_path do |f|
  #new-post-modal.modal.fade aria-hidden='true' role='dialog' tabindex='-1' 
    .modal-dialog role='document' 
      .modal-content
        .modal-header
          h5.modal-title New post
          button.close aria-label='Close' data-dismiss='modal' type='button' 
            span aria-hidden='true' &times;
        .modal-body
          .errors
          .form-group
            = f.label :title
            = f.text_field :title, class: 'form-control'
          .form-group.js-preview-image
            = f.label '', 'Image'
            br
            = image_tag "#{post_image_url(f.object.image_url)}", class: 'js-image image-preview'
            .custom-file
              = f.file_field :image, class: 'custom-file-input', onchange: 'previewImage(this); changeFileName(this)'
              = f.label :image, 'Choose file', class: 'custom-file-label'
          .form-group
            = f.label :content
            = f.text_area :content, class: 'form-control', rows: 4
        .modal-footer
          = f.button 'Close', class: 'btn btn-secondary', data: { dismiss: 'modal' }
          = f.button 'Save changes', class: 'btn btn-primary', type: 'submit'

app/views/posts/_form_edit.html.slim
= form_with model: post, url: post_path(post.id), method: :patch do |f|
  div(class='modal fade' aria-hidden='true' role='dialog' tabindex='-1' id="modal-#{post.id}") 
    .modal-dialog role='document' 
      .modal-content
        .modal-header
          h5.modal-title Edit post
          button.close aria-label='Close' data-dismiss='modal' type='button' 
            span aria-hidden='true' &times;
        .modal-body
          .edit-errors
          .form-group
            = f.label :title
            = f.text_field :title, class: 'form-control'
          .form-group.js-preview-image
            = f.label '', 'Image'
            br
            = image_tag "#{post_image_url(f.object.image_url)}", class: 'js-image image-preview'
            .custom-file
              = f.file_field :image, class: 'custom-file-input', onchange: 'previewImage(this); changeFileName(this)'
              = f.label :image, 'Choose file', class: 'custom-file-label'
          .form-group
            = f.label :content
            = f.text_area :content, class: 'form-control', rows: 4
        .modal-footer
          = f.button 'Close', class: 'btn btn-secondary', data: { dismiss: 'modal' }
          = f.button 'Save changes', class: 'btn btn-primary', type: 'submit'

app/views/posts/_form_edit_comment.slim
= form_with model: comment, url: post_comment_path(post_id: post_id, id: comment.id), method: :patch do |f|
  div(class='modal fade' aria-hidden='true' role='dialog' tabindex='-1' id="modal-#{comment.id}")
    .modal-dialog.modal-dialog-centered role="document" 
      .modal-content
        .modal-header
          h5#exampleModalLongTitle.modal-title Edit comment
          button.close aria-label="Close" data-dismiss="modal" type="button" 
            span aria-hidden="true"  &times;
        .modal-body
          = f.text_area :content, rows: 4, cols: 50
        .modal-footer
          = f.button 'Close', data: { dismiss: 'modal' }, class: 'btn btn-secondary'
          = f.button 'Save changes', class: 'btn btn-primary', type: 'submit'

app/views/posts/create.js.slim
| $(".errors").html("#{j render('shared/error_messages', object: @post)}");

app/views/posts/index.html.slim
.new-feed.text-center
  h2 New Feed

.new-post
  button.btn.btn-outline-success data-target="#new-post-modal" data-toggle="modal" type="button" 
    i.fas.fa-plus-circle>
    | New Post
  = render 'form', post: @post

.post-list
  - @posts.each do |post|
    - unless post.new_record?
      .card
        .row
          .col-sm-3
            = image_tag "#{post_image_url(post.image.thumb.url)}", class: 'd-block post-image'
          .col-sm-9
            .row
              .col-sm-11
              .col-sm-1.action
                .row
                  .col-sm-1.edit-post
                    = link_to '', data: { target: "#modal-#{post.id}", toggle: 'modal' } do
                      i.fas.fa-edit
                    = render 'form_edit', post: post 
                  .col-sm-1.delete-post
                    = link_to post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true do
                      i.fas.fa-trash
            .card-block
              h6 = link_to post.title, post_path(post.id) 
              p.post-content = post.content.truncate(40)

app/views/posts/show.html.slim
.post-detail
  h2.mt-4 = @post.title
  p.lead
    | by 
    a href="#" = @post.user.name
  hr
  p = l @post.created_at, format: :long
  hr
  = image_tag "#{post_image_url(@post.image_url)}" 
  hr
  p.lead = @post.content
  hr
  .card.my-4
    h5.card-header Leave a Comment:
    .card-body
      = form_with model: @comment, url: post_comments_path(post_id: @post.id) do |f|
        .form-group
          = f.text_area :content, rows: '3', class: 'form-control'                            
        = f.button 'Submit', class: 'btn btn-primary', type: 'submit'
  - @comments.each do |comment|
    .media.mb-4.comment-detail
      img.d-flex.mr-3.rounded-circle alt="" src="http://placehold.it/50x50"
      .media-body.row
        .col-sm-8
          h5.mt-0 = comment.user.name
          = comment.content
        .col-sm-4.row
          .col-sm-8.created-comment-time
            = l comment.created_at, format: :long
          .action.row
            .col-sm-1
              = link_to '', data: { target: "#modal-#{comment.id}", toggle: 'modal' } do
                i.fas.fa-edit
              = render 'form_edit_comment', post_id: @post.id, comment: comment 
            .col-sm-1
              = link_to post_comment_path(post_id: @post.id, id: comment.id), method: :delete,
                data: { confirm: 'Are you sure?' }, remote: true do
                i.fas.fa-trash

app/views/posts/update.js.slim
| $('.edit-errors').html("#{j render('shared/error_messages', object: @post)}");

app/views/shared/_error_messages.html.slim
- return if object.errors.blank?

.error-messages
  - object.errors.full_messages.each do |msg|
    li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |key, value|
  div(class="alert alert-#{flash_messae_class(key)}") = value

app/views/users/index.html.slim
.text-center
  h2 User List

.user-list
  - @users.each do |user|
    .card.user-detail-card
      .row
        .col-sm-3
          = image_tag 'https://via.placeholder.com/150', class: 'd-block post-image'
        .col-sm-9.user-detail-content
          .card-block
            h6 = link_to user.name, user_path(user.id) 
            p.post-content = user.email